boostyourbudget/boostyourbudget/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("home.urls")),
    path('login/', include("home.urls")),
    path('boost/', include("boost.urls")),
    path('expenses/', include("boost.urls")),
    path('register/', include("home.urls")),
    path("admin/", admin.site.urls),
]

boostyourbudget/home/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "home"
urlpatterns = [
        path('', views.home, name='home'),
        path('login/', views.loginPage, name='login'),
        path('logout/', views.logoutUser, name='logout'),
        path('register/', views.register, name='register'),
        path('admin/', admin.site.urls),    
]

boostyourbudget/home/models.py
from django.db import models

# Create your models here.

boostyourbudget/home/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

boostyourbudget/home/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from .forms import CreateUserForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout


def home(request):
    return render(request, 'home/index.html')


def loginPage(request):
    if request.user.is_authenticated:
        return redirect('boost:boost')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('boost:boost')
            else:
                messages.info(request, 'Username or password is incorrect!')

        context = {}
        return render(request, 'home/login.html', context)


def logoutUser(request):
    logout(request)
    return redirect('home:login')


def register(request):
    if request.user.is_authenticated:
        return redirect('boost:boost')
    
    else:
        form = CreateUserForm()

        if request.method == 'POST':
            form = CreateUserForm(request.POST)
            if form.is_valid():
                form.save()
                user = form.cleaned_data.get('username')
                messages.success(request, 'Account was created for ' + user)
                return redirect('home:login')

        context = {'form': form}
        return render(request, 'home/register.html', context)

boostyourbudget/home/templates/home/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewreport" content="width=device-width, initial-scale=1.0">
	<title>
		Boost Your Budget
	</title>
	<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" />
	<link href="https://fonts.googleapis.com/css?family=Raleway&display=swap" rel="stylesheet" />
	<link rel="stylesheet" href="{% static 'home/css/styles.css' %}">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
</head>
<body>
	<div class="container-fluid banner">
		<div class="row">
			<div class="col-md-12">
				<nav class="navbar navbar-md">
					<div class="navbar-brand">Boost Your Budget</div>
					<ul class="nav">
						<li class="nav-item">
							<a class="nav-link" href="{% url 'home:home' %}">HOME</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{% url 'home:login' %}">LOGIN</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="#">ABOUT</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="#">CONTACT</a>
						</li>
					</ul>
				</nav>
			</div>
			{% block content %}{% endblock content %}
		</div>
	</div>
</body>
</html>

boostyourbudget/home/templates/home/index.html
{% extends "home/base.html" %}

{% block content %}
    <div class="col-md-8 offset-md-2 info">
        <h1 class="text-center">Are you tired of not be able to save money?</h1>
        <p class="text-center">
            Click on the button below and discover the solution for it.
        </p>
        <a href="#" class="btn btn-md text-center">GET STARTED</a>
    </div>
{% endblock content %}

boostyourbudget/home/templates/home/login.html
{% extends "home/base.html" %}

{% block content %}
<div class="container h-100">
  <div class="d-flex justify-content-center h-100">
    <div class="user_card">
      <div class="d-flex justify-content-center">


        <h3 id="form-title">LOGIN</h3>
      </div>
      <div class="d-flex justify-content-center form_container">
        <form method="POST" action="">
          {% csrf_token %}
          <div class="input-group mb-3">
            <div class="input-group-append">
              <span class="input-group-text"><i class="fas fa-user"></i></span>
            </div>
            <input type="text" name="username" placeholder="Username..." class="form-control">
          </div>
          <div class="input-group mb-2">
            <div class="input-group-append">
              <span class="input-group-text"><i class="fas fa-key"></i></span>
            </div>
              <input type="password" name="password" placeholder="Password..." class="form-control" >
          </div>

            <div class="d-flex justify-content-center mt-3 login_container">
               <input class="btn login_btn" type="submit" value="Login">
               </div>
        </form>

      </div>

      {% for message in messages %}
        <p id='messages'>{{message}}</p>
      {% endfor %}
  
      <div class="mt-4">
        <div class="d-flex justify-content-center links">
          Don't have an account? <a href="{% url 'home:register' %}" class="ml-2">Sign Up</a>
        </div>
    
      </div>
    </div>
  </div>
</div>
{% endblock content %}

boostyourbudget/home/templates/home/register.html
{% extends "home/base.html" %}

{% block content %}
<div class="container h-100">
  <div class="d-flex justify-content-center h-100">
    <div class="user_card">
      <div class="d-flex justify-content-center">
        <h3 id="form-title">REGISTER ACCOUNT</h3>
      </div>
      <div class="d-flex justify-content-center form_container">

        <form method="POST" action="">
          {% csrf_token %}
          <div class="input-group mb-3">
            <div class="input-group-append">
              <span class="input-group-text"><i class="fas fa-user"></i></span>
            </div>
            {{form.username}}
          </div>
          <div class="input-group mb-2">
            <div class="input-group-append">
              <span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
            </div>
            {{form.email}}
          </div>
          <div class="input-group mb-2">
            <div class="input-group-append">
              <span class="input-group-text"><i class="fas fa-key"></i></span>
            </div>
            {{form.password1}}
          </div>
          <div class="input-group mb-2">
            <div class="input-group-append">
              <span class="input-group-text"><i class="fas fa-key"></i></span>
            </div>
            {{form.password2}}
          </div>

             <div class="d-flex justify-content-center mt-3 login_container">
             <input class="btn login_btn" type="submit" value="Register Account">
             </div>
        </form>
      </div>
      {{form.errors}}
      <div class="mt-4">
        <div class="d-flex justify-content-center links">
          Already have an account? <a href="{% url 'home:login' %}" class="ml-2">Login</a>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
          /* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
  //We start indexing at one because CSRF_token is considered and input field 
   */

  //Query All input fields
  var form_fields = document.getElementsByTagName('input')
  form_fields[1].placeholder='Username..';
  form_fields[2].placeholder='Email..';
  form_fields[3].placeholder='Enter password...';
  form_fields[4].placeholder='Re-enter Password...';


  for (var field in form_fields){	
    form_fields[field].className += ' form-control'
  }
</script>
{% endblock content %}