boostyourbudget/boost/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "boost"
urlpatterns = [
        path('', views.boost, name='boost'),
        # path('expenses/', views.expenses, name='expenses'),
        path('expenses/api/data', views.get_expense_api_data, name='api_expenses_data'),
        # path('incomes/', views.incomes, name='incomes'),
        # path('savings/', views.savings, name='savings'),
        # path('expenses/update_expense/<str:pk>', views.updateExpense, name='update_expense'),
        # path('expenses/update_savings/<str:pk>', views.updateSavings, name='update_savings'),
        # path('expenses/update_income/<str:pk>', views.updateIncome, name='update_income'),
        # path('expenses/delete_expense/<str:pk>', views.deleteExpense, name='delete_expense'),
        # path('expenses/delete_savings/<str:pk>', views.deleteSavings, name='delete_savings'),
        # path('expenses/delete_income/<str:pk>', views.deleteIncome, name='delete_income'),
        # path('expenses/expense_categories/', views.expensesCat, name='expense_categories'),
        # path('expenses/income_categories/', views.incomesCat, name='income_categories'),
        # path('expenses/savings_categories/', views.savingsCat, name='savings_categories'),
        # path('expenses/delete_expense_cat/<str:pk>', views.deleteExpenseCat, name='delete_expense_cat'),
        # path('expenses/delete_income_cat/<str:pk>', views.deleteIncomeCat, name='delete_income_cat'),
        # path('expenses/delete_savings_cat/<str:pk>', views.deleteSavingsCat, name='delete_savings_cat'),
        path('fin-data-add/<str:fintype>', views.finDataAdd, name='fin-data-add'),
        path('fin-data-add/<str:fintype>/fin-categories', views.finCatAdd, name='fin-categories'),
        path('fin-data-add/<str:fintype>/fin-data-update/<str:pk>', views.finDataUpdate, name='fin-data-update'),
        path('fin-data-add/<str:fintype>/fin-data-delete/<str:pk>', views.finDataDelete, name='fin-data-delete'),
        path('fin-data-add/<str:fintype>/fin-categories/fin-categories-delete/<str:pk>', views.finCatDelete, name='fin-categories-delete'),
]

boostyourbudget/boostyourbudget/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("home.urls")),
    path('login/', include("home.urls")),
    path('boost/', include("boost.urls")),
    path('expenses/', include("boost.urls")),
    path('register/', include("home.urls")),
    path("admin/", admin.site.urls),
]

boostyourbudget/home/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "home"
urlpatterns = [
        path('', views.home, name='home'),
        path('login/', views.loginPage, name='login'),
        path('logout/', views.logoutUser, name='logout'),
        path('register/', views.register, name='register'),
        path('admin/', admin.site.urls),    
]

boostyourbudget/home/models.py
from django.db import models

# Create your models here.

boostyourbudget/boost/forms.py
from django.forms import ModelForm
from .models import Expenses, ExpenseCategory, IncomeCategory, Incomes, Savings, SavingsCategory

class ExpenseForm(ModelForm):
    class Meta:
        model = Expenses
        fields = '__all__'
    
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(ExpenseForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'


class ExpenseCatForm(ModelForm):
    class Meta:
        model = ExpenseCategory
        fields = '__all__'
    
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(ExpenseCatForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'


class IncomeForm(ModelForm):
    class Meta:
        model = Incomes
        fields = '__all__'
    
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(IncomeForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'


class IncomeCatForm(ModelForm):
    class Meta:
        model = IncomeCategory
        fields = '__all__'
    
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(IncomeCatForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'



class SavingsForm(ModelForm):
    class Meta:
        model = Savings
        fields = '__all__'
    
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(SavingsForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'


class SavingsCatForm(ModelForm):
    class Meta:
        model = SavingsCategory
        fields = '__all__'
    
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(SavingsCatForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

boostyourbudget/home/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

boostyourbudget/boost/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Expenses, ExpenseCategory, IncomeCategory, Incomes, Savings, SavingsCategory
from .forms import ExpenseForm, ExpenseCatForm, IncomeForm, IncomeCatForm, SavingsCatForm, SavingsForm
from datetime import datetime
from django.db.models import Sum
from django.contrib.admin.views.decorators import staff_member_required
from django.http import JsonResponse
import pandas as pd


fin_dict = {'Expenses':
            [{'form': ExpenseForm},
             {'model': Expenses},
             {'categories': ExpenseCategory},
             {'cat_form': ExpenseCatForm},
             {'fyn_type': 'Expense'},
             {'fyn_type_plural': 'Expenses'}],
             "Incomes":
             [{'form': IncomeForm},
               {'model': Incomes},
               {'categories': IncomeCategory},
               {'cat_form': IncomeCatForm},
               {'fyn_type': 'Income'},
               {'fyn_type_plural': 'Incomes'}],
               "Savings":
             [{'form': SavingsForm},
               {'model': Savings},
               {'categories': SavingsCategory},
               {'cat_form': SavingsCatForm},
               {'fyn_type': 'Saving'},
               {'fyn_type_plural': 'Savings'}]}



def finDataAdd(request, fintype):
    form = fin_dict[fintype][0]['form']
    if request.method == 'POST':
        form = fin_dict[fintype][0]['form'](request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.user = request.user
            obj.date_created = datetime.now().today()
            obj.save()
            return redirect('boost:fin-data-add', fintype)
             
    database = fin_dict[fintype][1]['model'].objects.all()
    fin_type = fin_dict[fintype][4]['fyn_type']
    fin_type_plural = fin_dict[fintype][5]['fyn_type_plural']
    
    context = {'form': form,
               'database': database,
               'fin_type': fin_type,
               'fin_type_plural': fin_type_plural}
    
    return render(request, 'boost/fin-data-add.html', context)


@login_required(login_url='home:login')
def finCatAdd(request, fintype):
    
    form = fin_dict[fintype][3]['cat_form']
    if request.method == 'POST':
        form = fin_dict[fintype][3]['cat_form'](request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.user = request.user
            obj.date_created = datetime.now().today()
            obj.save()
            return redirect('boost:fin-categories', fintype)
            
    database = fin_dict[fintype][2]['categories'].objects.all()
    fin_type = fin_dict[fintype][4]['fyn_type']
    fin_type_plural = fin_dict[fintype][5]['fyn_type_plural']
    
    context = {'form': form,
               'database': database,
               'fin_type': fin_type,
               'fin_type_plural': fin_type_plural}
    
    
    return render(request, 'boost/fin-categories.html', context)


@login_required(login_url='home:login')
def finDataUpdate(request, fintype, pk):
    data = fin_dict[fintype][1]['model'].objects.get(id=pk)
    form = fin_dict[fintype][0]['form'](instance=data)
    if request.method == 'POST':
        form = fin_dict[fintype][0]['form'](request.POST, instance=data)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.user = request.user
            obj.save()
            
            return redirect('boost:fin-data-add', fintype)

    database = database = fin_dict[fintype][1]['model'].objects.all()
    fin_type = fin_dict[fintype][4]['fyn_type']
    fin_type_plural = fin_dict[fintype][5]['fyn_type_plural']
    
    context = {'form': form,
               'database': database,
               'fin_type': fin_type,
               'fin_type_plural': fin_type_plural}
    return render(request, 'boost/fin-data-update.html', context)


@login_required(login_url='home:login')
def finDataDelete(request, fintype, pk):
    data = fin_dict[fintype][1]['model'].objects.get(id=pk)

    if request.method == 'POST':
        data.delete()
        return redirect('boost:fin-data-add', fintype)

    fin_type = fin_dict[fintype][4]['fyn_type']
    fin_type_plural = fin_dict[fintype][5]['fyn_type_plural']
    context = {'data': data,
               'fin_type': fin_type,
               'fin_type_plural': fin_type_plural}
    return render(request, 'boost/fin-data-delete.html', context)


@login_required(login_url='home:login')
def finCatDelete(request, fintype, pk):
    category = fin_dict[fintype][2]['categories'].objects.get(id=pk)

    if request.method == 'POST':
        category.delete()
        return redirect('boost:fin-categories', fintype)

    fin_type = fin_dict[fintype][4]['fyn_type']
    fin_type_plural = fin_dict[fintype][5]['fyn_type_plural']
    context = {'data': category,
               'fin_type': fin_type,
               'fin_type_plural': fin_type_plural}
    return render(request, 'boost/fin-cat-delete.html', context)


def get_expense_api_data(request, *args, **kwargs):

    sort_order = ['January','February','March','April','May','June','July','August','September','October','November','December']

    exp_df = pd.DataFrame(Expenses.objects.filter(user=request.user).all().values('date_created', 'amount'))
    categories = dict()

    if exp_df.empty:
        default_items_exp = [0]
        labels_exp = [0]
    
    else:
        categories['expenses'] = pd.unique(pd.DataFrame(Expenses.objects.filter(user=request.user).all().values('categories')).categories.values).tolist()
    
        exp_df['date_created'] = pd.to_datetime(exp_df['date_created'])
        exp_df = pd.DataFrame(exp_df.groupby(exp_df['date_created'].dt.strftime('%B'))['amount'].sum())
        exp_df["date_created"] = exp_df.index
        exp_df.index = pd.CategoricalIndex(exp_df["date_created"], categories=sort_order, ordered=True)
        exp_df = exp_df.sort_index().reset_index(drop=True)

        default_items_exp = exp_df.amount.tolist()
        labels_exp = exp_df.date_created.tolist()
    
    inc_df = pd.DataFrame(Incomes.objects.filter(user=request.user).all().values('date_created', 'amount'))
    

    if inc_df.empty:
        default_items_inc = [0]
        labels_inc = [0]
    
    else:
        categories['incomes'] = pd.unique(pd.DataFrame(Incomes.objects.filter(user=request.user).all().values('categories')).categories.values).tolist()
        
        inc_df['date_created'] = pd.to_datetime(inc_df['date_created'])
        inc_df = pd.DataFrame(inc_df.groupby(inc_df['date_created'].dt.strftime('%B'))['amount'].sum())
        inc_df["date_created"] = inc_df.index
        inc_df.index = pd.CategoricalIndex(inc_df["date_created"], categories=sort_order, ordered=True)
        inc_df = inc_df.sort_index().reset_index(drop=True)
        
        default_items_inc = inc_df.amount.tolist()
        labels_inc = inc_df.date_created.tolist()
    try:
        net_df = pd.merge(inc_df, exp_df, how='outer', on='date_created')
        net_df = net_df.fillna(0)
        net_df['amount'] = net_df['amount_x'] - net_df['amount_y']
        net_df.index = pd.CategoricalIndex(net_df["date_created"], categories=sort_order, ordered=True)
        net_df = net_df.sort_index().reset_index(drop=True)

        default_items_net = net_df.amount.tolist()
        labels_net = net_df.date_created.tolist()

    except KeyError:
        if inc_df.empty:
            net_df = exp_df
        
        elif exp_df.empty:
            net_df = inc_df
        
        net_df.index = pd.CategoricalIndex(net_df["date_created"], categories=sort_order, ordered=True)
        net_df = net_df.sort_index().reset_index(drop=True)

        default_items_net = net_df.amount.tolist()
        labels_net = net_df.date_created.tolist()
        
    savings_df = pd.DataFrame(Savings.objects.filter(user=request.user).all().values('date_created', 'amount'))

    if savings_df.empty:
        default_items_savings = [0]
        labels_savings = [0]

    else:
        categories['savings'] = pd.unique(pd.DataFrame(Savings.objects.filter(user=request.user).all().values('categories')).categories.values).tolist()
        
        savings_df['date_created'] = pd.to_datetime(savings_df['date_created'])
        savings_df = pd.DataFrame(savings_df.groupby(savings_df['date_created'].dt.strftime('%B'))['amount'].sum())
        savings_df["date_created"] = savings_df.index
        savings_df.index = pd.CategoricalIndex(savings_df["date_created"], categories=sort_order, ordered=True)
        savings_df = savings_df.sort_index().reset_index(drop=True)

        default_items_savings = savings_df.amount.tolist()
        labels_savings = savings_df.date_created.tolist()

    labels = {'expenses': labels_exp, 
              'incomes': labels_inc,
              'net': labels_net,
              'savings': labels_savings}
    
    default_items = {'expenses': default_items_exp,
                     'incomes': default_items_inc,
                     'net': default_items_net,
                     'savings': default_items_savings}

    data = {
        'labels': labels,
        'default': default_items,
        'categories': categories
    }

    return JsonResponse(data, safe=False) 



@login_required(login_url='home:login')
def boost(request):

    expenses_total = Expenses.objects.filter(user=request.user).aggregate(Sum('amount'))

    if not expenses_total['amount__sum'] == None:
        expenses_total = expenses_total['amount__sum']
    else:
        expenses_total = 0
    
    incomes_total = Incomes.objects.filter(user=request.user).aggregate(Sum('amount'))

    if not incomes_total['amount__sum'] == None:
        incomes_total = incomes_total['amount__sum']
    else:
        incomes_total = 0

    savings_total = Savings.objects.filter(user=request.user).aggregate(Sum('amount'))

    if not savings_total['amount__sum'] == None:

boostyourbudget/home/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from .forms import CreateUserForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout


def home(request):
    return render(request, 'home/index.html')


def loginPage(request):
    if request.user.is_authenticated:
        return redirect('boost:boost')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('boost:boost')
            else:
                messages.info(request, 'Username or password is incorrect!')

        context = {}
        return render(request, 'home/login.html', context)


def logoutUser(request):
    logout(request)
    return redirect('home:login')


def register(request):
    if request.user.is_authenticated:
        return redirect('boost:boost')
    
    else:
        form = CreateUserForm()

        if request.method == 'POST':
            form = CreateUserForm(request.POST)
            if form.is_valid():
                form.save()
                user = form.cleaned_data.get('username')
                messages.success(request, 'Account was created for ' + user)
                return redirect('home:login')

        context = {'form': form}
        return render(request, 'home/register.html', context)

boostyourbudget/boost/templates/boost/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Boost</title>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.1/chart.min.js"></script>
  <link rel="stylesheet" href="https://cdn.datatables.net/2.0.3/css/dataTables.dataTables.css"/>
  <link rel="stylesheet" href="https://cdn.datatables.net/2.0.3/css/dataTables.bootstrap5.css" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/css/bootstrap.min.css"/>
  <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <!-- Custom CSS -->
  <link rel="stylesheet" href="{% static 'boost/css/styles.css' %}">
</head>
<body>

<!-- Left Menu (Sidebar) -->
{% comment %}  {% endcomment %}

<button class="btn btn-info" style="margin-left: 2rem; margin-top: 2rem; " type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasWithBothOptions" aria-controls="offcanvasWithBothOptions">
  <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-house" viewBox="0 0 16 16">
    <path d="M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.708L2 8.207V13.5A1.5 1.5 0 0 0 3.5 15h9a1.5 1.5 0 0 0 1.5-1.5V8.207l.646.647a.5.5 0 0 0 .708-.708L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293zM13 7.207V13.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V7.207l5-5z"/>
  </svg>
</button>

<div class="offcanvas offcanvas-start" data-bs-scroll="true" tabindex="-1" id="offcanvasWithBothOptions" aria-labelledby="offcanvasWithBothOptionsLabel">
  <div class="offcanvas-header">
    <h5 class="offcanvas-title" id="offcanvasWithBothOptionsLabel">Menu</h5>
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <div class="offcanvas-body">
    <div class="sidebar">
      <a href="#">{{request.user}} Profile</a>
      <a href="{% url 'boost:boost' %}">Home</a>
      <a href="{% url 'boost:fin-data-add' 'Expenses'%}">Expenses</a>
      <a href="{% url 'boost:fin-data-add' 'Incomes' %}">Incomes</a>
      <a href="{% url 'boost:fin-data-add' 'Savings' %}">Savings</a>
      <a href="#">About</a>
      <a href="#">Services</a>
      <a href="{% url "home:logout" %}">Logout</a>
    </div>
  </div>
</div>

{% block content %}{% endblock content %}

<!-- Bootstrap JS (optional, for Bootstrap components) -->

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script src="https://code.jquery.com/jquery-3.7.1.js"></script>
<script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.datatables.net/2.0.3/js/dataTables.bootstrap5.js"></script>

</body>
</html>

boostyourbudget/boost/templates/boost/fin-cat-delete.html
{% extends "boost/base.html" %}

{% block content %}
<!-- Main Content Area -->

<div class="content" id="content">
    <h2>Delete {{fin_type}} Category</h2>
    <p>Are you sure you wanna delete?</p>

    <p>Name: {{data.name}}</p>
    <p>Date: {{data.date_created}}</p>
    <form method='POST' action="{% url "boost:fin-categories-delete" fintype=fin_type_plural pk=data.id %}">
      {% csrf_token %}
      <a class="btn btn-sm btn-info" href="{% url "boost:fin-data-add" fin_type_plural %}">Cancel</a>
      <input class="btn btn-sm btn-danger" value="Confirm" type="submit" name="Confirm">
    </form>
</div>
  <!-- Bootstrap JS (optional, for Bootstrap components) -->
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
{% endblock content %}

boostyourbudget/boost/templates/boost/fin-categories.html
{% extends "boost/base.html" %}
{% load static %}
{% block content %}
<!-- Main Content Area -->
<div class="content" id="content">
    <h2>Add {{fin_type}} Category</h2>
    <form method='POST'>
      {% csrf_token %}
      <div class="form-group">
        <label>{{fin_type}} Category Name:</label>
        {{form.name}}
      </div>
      <button type="submit" class="btn btn-primary">Add {{fin_type}} Category</button>
    </form>
    <br>
    <h2>{{fin_type}} Categories</h2>
    <table id='model' class="table table-striped">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Date</th>
          <th scope="col">{{fin_type}} Category Name</th>
          <th scope="col">Remove</th>
        </tr>
      </thead>
      <tbody>
        {% for data in database %}

          <tr>
            <td>{{data.id}}</td>
            <td>{{data.date_created}}</td>
            <td>{{data.name}}</td>
            <td><a href="{% url "boost:fin-categories-delete" fintype=fin_type_plural pk=data.id %}" class="btn btn-sm btn-danger">X</a></td>
          </tr>

        {% endfor %}

      </tbody>
    </table>
  </div>
  <script src="{% static 'boost/js/table_model.js' %}"></script>
  <!-- Bootstrap JS (optional, for Bootstrap components) -->
{% endblock content %}

boostyourbudget/boost/templates/boost/fin-data-add.html
{% extends "boost/base.html" %}
{% load static %}
{% block content %}
<!-- Main Content Area -->
<div class="content" id="content">
    <h2>Add {{fin_type_plural}}</h2>
    <form method='POST'>
      {% csrf_token %}
      <div class="form-group">
        <label>{{fin_type}} Name:</label>
        {{form.name}}
      </div>
      <div class="form-group">
        <label>{{fin_type}} Category:</label>
        {{form.categories}}
        <a href="{% url "boost:fin-categories" fintype=fin_type_plural %}">Manage {{fin_type}} categories</a>
      </div>
      <div class="form-group">
        <label>{{fin_type}} Amount:</label>
        {{form.amount}}
      </div>
      <button type="submit" class="btn btn-primary">Add {{fin_type}}</button>
    </form>
    <br>
    <h2>{{fin_type_plural}}</h2>
    <table id='model' class="table table-striped">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Date</th>
          <th scope="col">{{fin_type}} Name</th>
          <th scope="col">Category</th>
          <th scope="col">Amount</th>
          <th scope="col">Update</th>
          <th scope="col">Remove</th>
        </tr>
      </thead>
      <tbody>
        {% for data in database %}

        {% if data.user == request.user %}
          <tr>
            <td>{{data.id}}</td>
            <td>{{data.date_created}}</td>
            <td>{{data.name}}</td>
            <td>{{data.categories}}</td>
            <td>{{data.amount}}</td>
            <td><a href="{% url "boost:fin-data-update" fintype=fin_type_plural pk=data.id %}" class="btn btn-sm btn-info">O</a></td>
            <td><a href="{% url "boost:fin-data-delete" fintype=fin_type_plural pk=data.id %}" class="btn btn-sm btn-danger">X</a></td>
          </tr>
        {% endif %}
        {% endfor %}

      </tbody>
    </table>
  </div>
  
  <!-- Bootstrap JS (optional, for Bootstrap components) -->
  <script src="{% static 'boost/js/table_model.js' %}"></script>
{% endblock content %}

boostyourbudget/boost/templates/boost/fin-data-delete.html
{% extends "boost/base.html" %}

{% block content %}
<!-- Main Content Area -->

<div class="content" id="content">
    <h2>Delete {{fin_type}}</h2>
    <p>Are you sure you wanna delete?</p>

    <p>Name: {{data.name}}</p>
    <p>Date: {{data.date_created}}</p>
    <p>Amount: {{data.amount}}</p>
    <form method='POST' action="{% url "boost:fin-data-delete" fintype=fin_type_plural pk=data.id %}">
      {% csrf_token %}
      <a class="btn btn-sm btn-info" href="{% url "boost:fin-data-add" fintype=fin_type_plural %}">Cancel</a>
      <input class="btn btn-sm btn-danger" value="Confirm" type="submit" name="Confirm">
    </form>
</div>
  <!-- Bootstrap JS (optional, for Bootstrap components) -->
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
{% endblock content %}

boostyourbudget/boost/templates/boost/fin-data-update.html
{% extends "boost/base.html" %}

{% block content %}
<!-- Main Content Area -->
<div class="content" id="content">
    <h2>Update {{fin_type}}</h2>
    <form method='POST'>
      {% csrf_token %}
      <div class="form-group">
        <label>{{fin_type}} Name:</label>
        {{form.name}}
      </div>
      <div class="form-group">
        <label>{{fin_type}} Category:</label>
        {{form.categories}}
      </div>
      <div class="form-group">
        <label>{{fin_type}} Amount:</label>
        {{form.amount}}
      </div>
      <div class="form-group">
        <label>Date:</label>
        {{form.date_created}}
      </div>
      <button type="submit" class="btn btn-primary">Edit</button>
    </form>
  
  <!-- Bootstrap JS (optional, for Bootstrap components) -->
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
{% endblock content %}